### ISSUE TITLE
Implicit string cast from RawByteString to String

### ISSUE THREAD

**Issue by ludan508** [bambucode/tfacturaelectronica#106]
Buen día, descargue el codigo para realizar pruebas en Rad Studio Tokyo, pero al momento de querer ejecutar me manda el error:

Implicit string cast from 'RawByteString' to 'string'

en el archivo Facturacion.ComprobanteV33

no he podido encontrar la solución, que sugieren?

**Comment by mr-E** [comment]
Aún no intento usar este proyecto en D.Tokyo, pero por si acaso voy dejando unas notas:
[System.RawByteString](http://docwiki.embarcadero.com/Libraries/Tokyo/en/System.RawByteString)

> type RawByteString = AnsiString;
> Description:  Enables the passing of string data of any code page without doing any codepage conversions.
> The purpose of RawByteString is to reduce the need for multiple overloads of procedures that read string data. This means that parameters of routines that process strings without regard for the string's code page should typically be of type RawByteString.
> RawByteString should only be used as a parameter type, and only in routines which otherwise would need multiple overloads for AnsiStrings with different codepages. Such routines need to be written with care for the actual codepage of the string at run time.
> In general, it is recommended that string processing routines should simply use "string" as the string type. Declaring variables or fields of type RawByteString should rarely, if ever, be done, because this practice can lead to undefined behavior and potential data loss. 

1.  [W1057 Implicit string cast from '%s' to '%s' (Delphi)](http://docwiki.embarcadero.com/RADStudio/Tokyo/en/W1057_Implicit_string_cast_from_%27%25s%27_to_%27%25s%27_(Delphi))
2. [Why does Delphi warn when assigning ShortString to string?](https://stackoverflow.com/questions/2121265/why-does-delphi-warn-when-assigning-shortstring-to-string)

**Comment by lcarrasco** [comment]
@ludan508 @mr-E El problema es que el proyecto Ejemplo está configurado para tratar los Warnings como errores. Fue un problema de omisión. Para poder correrlo solo es cuestión de desactivar esa opción:

https://groups.google.com/d/msg/tfacturaelectronica/ajcwyTre76Y/rkXZ9VX9BwAJ
