### ISSUE TITLE
Agregar el NODO Cuenta Predial CFDI Ver 3.3

### ISSUE THREAD

**Issue by thinkerbadal** [bambucode/tfacturaelectronica#112]
Saludos, Amigos
Permitanme Felicitarlos a TODOS por la creación de la Liberia TFacturaElectronica para DELPHI
Paso a los siguiente son usuario de la Librería ahora con la ver 3.3 necesito pedirles si pueden agregar
el NODO Cuenta Predial Anexo Imagen
![nodo_cuenta_predial](https://user-images.githubusercontent.com/6216503/30913342-7d272eb4-a355-11e7-86ac-e5c4055513c2.jpg)

Se preguntaran porque. .. porque en el Anexo 20 Publicado en el SAT para las Ayuntamientos es requerido:
[GuiaAnexo20DPA facturacion electronica_Ayunta.zip](https://github.com/bambucode/tfacturaelectronica/files/1337099/GuiaAnexo20DPA.facturacion.electronica_Ayunta.zip)

Anexo 20 
Guía de llenado de los CFDI emitidos
por la Federación, Entidades,
Entidades Federativas y los 
Municipios por Contribuciones,
Derechos, Productos, 
Aprovechamientos, Apoyos y
Estímulos que otorguen 

Espero que sea agregado para mayor Funcionalidad de la Liberia. ..GRACIAS

**Comment by lcarrasco** [comment]
Hola @thinkerbadal gracias por tus comentarios y sugerencia. Debido a que en nuestra empresa no tenemos necesidad de usar ese nodo y dado el trabajo que tenemos actualmente sería algo que tendrías que implementar por tu cuenta o esperar a que alguien más lo hiciera.

De entrada te comento que no debe ser complicado pues en esta versión de la librería se hace uso directo de la interfase del XSD lo cual expone todas las propiedades de CFDI 3.3 por ejemplo aquí ya puedes ver que puedes acceder a la propiedad `CuentaPredial`:

https://github.com/bambucode/tfacturaelectronica/blob/5e4831f204be01d422a9c8944bf7deda8dfc9564/Versiones/Facturacion.ComprobanteV33.pas#L245

Sugiero intentes implementarlo por tu cuenta y/o experimentes y cuando te topes con algún problema lo expongas para poder guiarte.

**Comment by fduenas** [comment]
HOla @lcarrasco. cuando te referies a implmentarlo por tu cuenta, si ya se expone en el XSD y en la interfaz y objecto, ¿que más sería necesario implementar?

**Comment by lcarrasco** [comment]
@fduenas En realidad creo que solo sería hacer pruebas, creo que al ya estar expuesto en el XSD y en la interface/objeto solo es cuestión de usar el nodo y llenarlo.

**Comment by thinkerbadal** [comment]
Saludos, @Fduenas @lcarrasco , como sería implementarlo dentro del EjemploFacturaElectronica, para que este mas completo el ejemplo de la Liberia

Gracias por sus respuestas

**Comment by fduenas** [comment]
@thinkerbadal : pues pienso que con solo llamar a la propiedad cuentaPredial.numero del comprobante V33



/tfacturaelectronica/Ejemplo/EjemploFacturaElectronica.dpr
Línea 212
-------------
concepto33 := Conceptos.Add;
...
...
concepto33.CuentaPredial.Numero := 'xxxxxxxxxxx';
------------

**Comment by thinkerbadal** [comment]
@fduenas como comentas agregue la linea en este orden:

 concepto33 := Conceptos.Add;
              concepto33.ClaveProdServ    := '52161529';  // De catálogo
              concepto33.NoIdentificacion := '1';
              concepto33.Cantidad         := '1';
              concepto33.ClaveUnidad      := 'EA';  // De catálogo
              concepto33.Unidad           := 'PZA'; // De catálogo
              concepto33.Descripcion      := 'Concepto No 1';
              concepto33.ValorUnitario    := '100.00';
              concepto33.Importe          := '100.00';
              concepto33.Descuento        := '0.00';
              concepto33.CuentaPredial.Numero:= '235989';

y al copilar el ejemplo de la libreria marca esto:
![error_lib_tfact](https://user-images.githubusercontent.com/6216503/31620952-2f0d3404-b25e-11e7-8bfe-51f5947af81d.png)

**Comment by lcarrasco** [comment]
@thinkerbadal Se te fijas en el mensaje, aparece algo como : `Concepto with Anonymous type found <cfdi:Impuestos>`. En este caso **a diferencia de la versión anterior el orden en que llenas la instancia importa** pues es el orden en que se genera el XML. 

De acuerdo a la [Guía de Llenado de CFDI 3.3 del SAT](http://www.sat.gob.mx/informacion_fiscal/factura_electronica/Documents/Gu%C3%ADaAnexo20.pdf), el dato de cuenta predial debe de ir justo después de los nodos de impuestos del concepto, por lo que creo que puede funcionar así:

```pascal
...
concepto33.Importe := '100.00';
// Primero indicamos los impuestos del nodo
iva33 := concepto33.Impuestos.Traslados.Add;
iva33.Base        := '100.00';
iva33.Impuesto    := '002';
iva33.TipoFactor  := 'Tasa';
iva33.TasaOCuota  := '0.160000';
iva33.Importe     := '16.00';
// Al final agregamos los datos de la cuenta predial
concepto33.CuentaPredial.Numero := '234989';
```

De igual manera si te sigue fallando te recomiendo subas el XML que te genera la librería para que otros podamos analizarla en alguna oportunidad o bien uses otras herramientas de validación que te ayuden a detectar el error.

Pero vás bien, creo que ya estás cerca de lograrlo.

**Comment by thinkerbadal** [comment]
Excelente @lcarrasco, @fduenas ¡¡GRACIAS!!, ahora si esta completo el ejemplo de la Libreria aqui anexo el code 

// Nodo de: Impuestos -> En este nodo se pueden expresar los impuestos aplicables a cada concepto.
              iva33 := concepto33.Impuestos.Traslados.Add;
              iva33.Base        := '100.00';
              iva33.Impuesto    := '002';
              iva33.TipoFactor  := 'Tasa';
              iva33.TasaOCuota  := '0.160000';
              iva33.Importe     := '16.00';

              // Nodo de: Cuenta Predial
              concepto33.CuentaPredial.Numero := '234989';

              // Nodo: Traslados ->En este nodo se pueden expresar los impuestos trasladados aplicables a cada concepto.
              Impuestos.TotalImpuestosTrasladados  := '16.00';

              // Nodo: Traslado ->En este nodo se debe expresar la información detallada de un traslado de impuestos aplicable a cada concepto.
              totalIVA33 := Impuestos.Traslados.Add;
              totalIVA33.Impuesto := '002';
              totalIVA33.TipoFactor := 'Tasa';
              totalIVA33.TasaOCuota := '0.160000';
              totalIVA33.Importe    := '16.00';

:+1:

**Comment by thinkerbadal** [comment]
<?xml version="1.0"?>

-<cfdi:Comprobante Sello="E/sWxvJUOWctFsB8mx+Q4vpiRklhpbfkWCkejxtTdP/RQN13Kdc48CPJEcMZTiIXJRRPtBgimJIcoF9q7KmQvEHWQVoEhWoSQmqZJDXrS9Yl6OCO8HGmyx5NX2B9Pa51W2BcKihxDpmDc+DHQYGj4SjmWjSrfLBqhRDKdtrUIbH1Bqk+y9VYIgGisBb238FSzwdCndAyb2yOcutGM7QuJNtc8NBXmHifMo97J3i+8CfjoEUWSrPOOcsadQr8/9loElZ9u5Qx7AvSUltrtZfjDg8nNNyqXaFSfI3pt43mHZh6kbOoM5WqxgKohba16xgRpZsJ1h9/DVJPmFHBNrSNmw==" xmlns:implocal="http://www.sat.gob.mx/implocal" LugarExpedicion="76030" MetodoPago="PUE" TipoDeComprobante="I" Total="116.00" TipoCambio="1" Moneda="MXN" Descuento="0.00" SubTotal="100.00" CondicionesDePago="Credito a 30 dias" FormaPago="01" Certificado="MIIGBzCCA++gAwIBAgIUMjAwMDEwMDAwMDAzMDAwMjI4MTcwDQYJKoZIhvcNAQELBQAwggFmMSAwHgYDVQQDDBdBLkMuIDIgZGUgcHJ1ZWJhcyg0MDk2KTEvMC0GA1UECgwmU2VydmljaW8gZGUgQWRtaW5pc3RyYWNpw7NuIFRyaWJ1dGFyaWExODA2BgNVBAsML0FkbWluaXN0cmFjacOzbiBkZSBTZWd1cmlkYWQgZGUgbGEgSW5mb3JtYWNpw7NuMSkwJwYJKoZIhvcNAQkBFhphc2lzbmV0QHBydWViYXMuc2F0LmdvYi5teDEmMCQGA1UECQwdQXYuIEhpZGFsZ28gNzcsIENvbC4gR3VlcnJlcm8xDjAMBgNVBBEMBTA2MzAwMQswCQYDVQQGEwJNWDEZMBcGA1UECAwQRGlzdHJpdG8gRmVkZXJhbDESMBAGA1UEBwwJQ295b2Fjw6FuMRUwEwYDVQQtEwxTQVQ5NzA3MDFOTjMxITAfBgkqhkiG9w0BCQIMElJlc3BvbnNhYmxlOiBBQ0RNQTAeFw0xNjEwMjUyMTU3NTZaFw0yMDEwMjUyMTU3NTZaMIHzMTAwLgYDVQQDEydSQURJT0dSQUZJQVMgSU5EVVNUUklBTEVTIERFTCBDRU5UUk8gQUMxMDAuBgNVBCkTJ1JBRElPR1JBRklBUyBJTkRVU1RSSUFMRVMgREVMIENFTlRSTyBBQzEwMC4GA1UEChMnUkFESU9HUkFGSUFTIElORFVTVFJJQUxFUyBERUwgQ0VOVFJPIEFDMSUwIwYDVQQtExxWT0M5OTAxMjlJMjYgLyBGVUFCNzcwMTE3QlhBMR4wHAYDVQQFExUgLyBGVUFCNzcwMTE3TURGUk5OMDkxFDASBgNVBAsUC1BydWViYV9DRkRJMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlO2ox7F9hB1xqkVlkonG1ZLvxh9d1tW/fEHu4vssixClDB/QhAYjQwXZY33IYGOs2Cfhzm/ApqsXJUp+Kp2Xu8TEW744+LCIIt12RoHl4UBLuWyUafPsgMO3bsLIDMpAGU7b7+qAShN8gQiePD8aCy/86wzPoInhLfZ2r59/ozn4TzcAMAqX2e/M8o3jSuLxlgNyVqQLSjNy8rddB89oVn51APDt/CWuha5f9BJ47X6sVqr3ZRXicuwbAnoZVovX1XoLt8YEP2sm10Jm4+OO+rHGLM/OBqA6AZvIfPe3Z32cijkrRRz9+nmRTSrZQkjJpYKglEZRDgV+wpt9cYYiAQIDAQABox0wGzAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwIGwDANBgkqhkiG9w0BAQsFAAOCAgEAVlOG4eH705Rl3BKjvKqs1+JJAzJbRD738gp5d1nQk6sfGYqer0AGpK0VXqmteThRNr/KrtJg73iwr0dfvSYzZ+Krzf6PMHGzENIDdcVzcfOw3Q5v7Pj/9KEqVJGMQQXOPjoJ2fe4E8A7TKh0zkQRZezNGmZwL7SMQPQwtgfYxUMh1jBdbCLMBzurg9thOsJyrBn49k1HjwB3HBMgZktdm5Kdg1ypCRjQcFTpKog2aWIl38nZCpWs5eheeOJgn28U6kX0TW0JqSEUwHpO6y8pWnffTL9/rKc6CxQwQRarV4qmiJrdeFq3cgk79sRgQA0fltYDB8DLF7Hkdji74glUZtrMD2XKoGMOSJrhlDJU7kphIOawVk1zbEON2rz3vt+NX02ovZct9Wg9lsI8FpQUcufa03vBkY3CUONPY9QUIDKw+y4Ng4+WijByUMshYBWiZRKSZF6o4fJdj1kVUTktYZvUdB+CarxRWKt+Ga+xwztYCVfzWJSrxvD9jcynqWPKNy4m3IgJRZ4oCiwVAsSinMRG0INUMJaSYAqa5dhyzXlg/1s0cjb4rewaypxV+S4pmW7CVci2ZWZG6QICsh+2MeX9DaW2SYl0JFlCDmSiRIE8yvryw3S2v7MRN0ltqMNPnOmlUc8qPEVZ9OfClm39abKIe1PWI7TZ/1rM+dE4ucU=" NoCertificado="20001000000300022817" Fecha="2017-10-16T14:27:35" Folio="603909167" Serie="Ver33" xmlns:cfdi="http://www.sat.gob.mx/cfd/3" Version="3.3" xsi:schemaLocation="http://www.sat.gob.mx/TimbreFiscalDigital http://www.sat.gob.mx/sitio_internet/cfd/timbrefiscaldigital/TimbreFiscalDigitalv11.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

<cfdi:Emisor RegimenFiscal="601" Nombre="RADIOGRAFIAS INDUSTRIALES DEL CENTRO AC" Rfc="VOC990129I26"/>

<cfdi:Receptor Nombre="Juan & José & 'Niño' & "Niña"" Rfc="MTI0806042N7" UsoCFDI="G01"/>


-<cfdi:Conceptos>


-<cfdi:Concepto Descuento="0.00" Importe="100.00" ValorUnitario="100.00" Descripcion="Concepto No 1" Unidad="PZA" ClaveUnidad="EA" Cantidad="1" NoIdentificacion="1" ClaveProdServ="52161529">


-<cfdi:Impuestos>


-<cfdi:Traslados>

<cfdi:Traslado Importe="16.00" TasaOCuota="0.160000" TipoFactor="Tasa" Impuesto="002" Base="100.00"/>

</cfdi:Traslados>

</cfdi:Impuestos>

<cfdi:CuentaPredial Numero="234989"/>

</cfdi:Concepto>

</cfdi:Conceptos>


-<cfdi:Impuestos TotalImpuestosTrasladados="16.00">


-<cfdi:Traslados>

<cfdi:Traslado Importe="16.00" TasaOCuota="0.160000" TipoFactor="Tasa" Impuesto="002"/>

</cfdi:Traslados>

</cfdi:Impuestos>


-<cfdi:Complemento>


-<implocal:ImpuestosLocales xmlns:implocal="http://www.sat.gob.mx/implocal" TotaldeRetenciones="0.00" TotaldeTraslados="1.00" version="1.0">

<implocal:TrasladosLocales Importe="1.00" TasadeTraslado="0.01" ImpLocTrasladado="Otro"/>

</implocal:ImpuestosLocales>

<tfd:TimbreFiscalDigital Version="1.1" xsi:schemaLocation="http://www.sat.gob.mx/TimbreFiscalDigital http://www.sat.gob.mx/sitio_internet/cfd/timbrefiscaldigital/TimbreFiscalDigitalv11.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" RfcProvCertif="DAL050601L35" SelloSAT="aVPrMjX745IQ5FapYgtD9b9n4IJNVgaLhvDeYihpnwAmBpdYrCfsmJ5dBLCTWHBEMDX9LGSmKiCIUFhYjXTNVeVoVjVImHKHb3jX2Wp3QDyAZuNKr9Pa34QrXTnMJqIp4ZcWt9ooH6D4Izv1IMMT9JFRNJfQNSSjpUWjoOf9SE9DFEe8w8T0RzpYiool7u8euqRc39msx+O5sbqGuEcp+bDv/ZHucgWtcxTw+1QTEBOGRsMKmg5JfoFkNA0B6A8cfuiiNHknLOiVeBc73xd4dVO+RUQrUIzhPpN5npKZkXekBsyR0baNGo+oJUuq7XxGnv2l9CnvTpJTlYuE4l0tCA==" NoCertificadoSAT="20001000000300022323" SelloCFD="E/sWxvJUOWctFsB8mx+Q4vpiRklhpbfkWCkejxtTdP/RQN13Kdc48CPJEcMZTiIXJRRPtBgimJIcoF9q7KmQvEHWQVoEhWoSQmqZJDXrS9Yl6OCO8HGmyx5NX2B9Pa51W2BcKihxDpmDc+DHQYGj4SjmWjSrfLBqhRDKdtrUIbH1Bqk+y9VYIgGisBb238FSzwdCndAyb2yOcutGM7QuJNtc8NBXmHifMo97J3i+8CfjoEUWSrPOOcsadQr8/9loElZ9u5Qx7AvSUltrtZfjDg8nNNyqXaFSfI3pt43mHZh6kbOoM5WqxgKohba16xgRpZsJ1h9/DVJPmFHBNrSNmw==" FechaTimbrado="2017-10-16T14:27:46" UUID="3ACE600A-2BAD-43F9-8A58-06019AE5855B" xmlns:tfd="http://www.sat.gob.mx/TimbreFiscalDigital"/>

</cfdi:Complemento>

</cfdi:Comprobante>
