### ISSUE TITLE
Cancelar el CFDI y obtener el Acuse

### ISSUE THREAD

**Issue by thinkerbadal** [bambucode/tfacturaelectronica#117]
Saludos Alguien porfavor me puede orientar, como poder cancelar el CFDI v3.3 y obtener el Acuse de cancelación. . usando la Libreria TFacturaElectronica. . .gracias. . .espero

**Comment by thinkerbadal** [comment]
Ayuda para CANCELAR el CFDI y obtener el ACUSE

uses Facturacion.Comprobante, Facturacion.ComprobanteV33, Facturacion.OpenSSL,
     Facturacion.PAC.Ecodex, Facturacion.ProveedorAutorizadoCertificacion, Facturacion.CertificadoDeSellos;

Var
  Recibo_XML : WideString;
  ReciboACancelar : IComprobanteFiscal;
  Pac: IProveedorAutorizadoCertificacion;
  CertificadoSellos: ICertificadoDeSellos;
  CredencialesPAC : TFacturacionCredencialesPAC;
  RutaCertificado, RutaLlavePrivada, ClaveLlavePrivada: string;
Const
  _URL_ECODEX_PRUEBAS_V33 = 'https://wsdev.ecodex.com.mx:2045';

Recibo_XML:= Busqueda_INGFm.UniQ_Ingresos.FieldByName('FE_TIMBRE_XML').AsVariant;
  ReciboACancelar:= TFacturaElectronica.Create;
  ReciboACancelar.XML:= Recibo_XML;

  ProveedorTimbrado:= TPACEcodex.Create(_URL_ECODEX_TSOFT);
  Try
    // El primer sello es para Ecodex
    RutaCertificado  := ExtractFilePath(Application.ExeName) + 'CSD_SAT\MHU800101Q70.cer';
    RutaLlavePrivada := ExtractFilePath(Application.ExeName) + 'CSD_SAT\MHU800101Q70.key';
    ClaveLlavePrivada:= Busqueda_INGFm.UniQ_SIS_Datos.FieldByName('CSD_PW').AsString;

    OpenSSL:= TOpenSSL.Create;
    OpenSSL.AsignarLlavePrivada(rutaLlavePrivada, claveLlavePrivada);

    CertificadoSellos:= TCertificadoDeSellos.Create;
    CertificadoSellos.Leer(rutaCertificado);

    // Verificando certificado de sellos y llave privada... sean pareja
    IF Not openSSL.SonPareja(RutaCertificado, RutaLlavePrivada, ClaveLlavePrivada) Then
    Begin
     Application.MessageBox('Los Archivos de Certificado y Llave Privada No Son Pareja. Favor de Verificar','Certificado SAT SCAMi Recaudación',mb_Ok+mb_iconInformation);
     Exit;
    End;

    //Writeln('Creando instancia de PAC...'); // Configuramos al PAC con los datos para pruebas
    Pac:= TProveedorEcodex.Create;
    CredencialesPAC.RFC           := Busqueda_INGFm.UniQ_SIS_Datos.FieldByName('RFC').AsString;
    CredencialesPAC.DistribuidorID:= Busqueda_INGFm.UniQ_SIS_Datos.FieldByName('ID_INTEGRADOR_PAC').AsString;

    // Asignamos nuestras credenciales de acceso con el PAC (en caso de Ecodex asignamos la credencial como usuario e integrador)
    ProveedorTimbrado.AsignarCredenciales(CredencialesPAC, CredencialesPAC);

    // Para cancelar el CFDI simplemente hacemos la siguiente llamada
    ReciboACancelar.XML:= Recibo_XML;
    IF ProveedorTimbrado.CancelarDocumento(ReciboACancelar.XML) Then
    Begin
     With UniQ_Operations Do
     Begin
      Close;
      SQL.Clear;
      SQL.Add('UPDATE ING_RECIBOS');
      SQL.Add('SET C_CANCEL = ''' + Trim(UpperCase(Causa.Text)) + ''', ');
      SQL.Add('STATUS = ''CA'''+', ');
      SQL.Add('PC_UPDATE = ''' + Terminal + ''' ');
      SQL.Add('WHERE EJERCICIO = ' + MenuGralFm.UniQ_Ejercicio.FieldByName('EJERCICIO').AsString + '');
      SQL.Add('AND RECIBO = ''' + Busqueda_INGFm.UniQ_Ingresos.FieldByName('RECIBO').AsString + '''');
      ExecSQL;
     End;
     MenuGralFm.UniTransactionWrite.CommitRetaining;

     Application.MessageBox('El FOLIO CFDI SELECCIONADO FUE CANCELADO CORRECTAMENTE, Verificarlo en la Opcion CONSULTAR','Recaudación Mpal.',mb_Ok+mb_iconInformation);
     Btn_CancelarClick(Sender);
    End
    Else
      Application.MessageBox('El FOLIO CFDI NO PUEDE SER CANCELADO CORRECTAMENTE, Verificarlo','Recaudación Mpal.',mb_Ok+mb_iconInformation);
  Finally
    ProveedorTimbrado.Free;
    FreeAndNil(ReciboACancelar);

para corregir, agregar lineas code las que faltan, porfavor

**Comment by lcarrasco** [comment]
Hola @thinkerbadal Si estás trabajando con Ecodex, chécate el branch manejo-errores-ecodex donde ya están los métodos de cancelado y obtención de acuse:
https://github.com/bambucode/tfacturaelectronica/commit/fde645a7c030e566862fe5151753c42f4703b573

**Comment by thinkerbadal** [comment]
Saludos **@lcarrasco**  me puede asesorar que le falta a este code para que funcione al 100%, ?

implementation

uses MenuGralUnit, Busqueda_INGUnit, EcodexWsCancelacion,Facturacion.Comprobante, Facturacion.CertificadoDeSellos,
  Facturacion.OpenSSL, Facturacion.PAC.Ecodex, Facturacion.ProveedorAutorizadoCertificacion;
procedure TBusqueda_ING_CancelFm.Btn_AceptarClick(Sender: TObject);
Var
  NFolio_XML : WideString;
  Cancelar_UUID: TEcodexSolicitudCancelaMultiple;
  Solicitar_Acuse: TEcodexSolicitudAcuse;
  Recuperar_Acuse: TEcodexRespuestaRecuperarAcuse;

  OpenSSL : IOpenSSL;
  XmlTimbre : TCadenaUTF8;
  Pac: IProveedorAutorizadoCertificacion;
  CertificadoSellos: ICertificadoDeSellos;
  CredencialesPAC : TFacturacionCredencialesPAC;

  QueVersion, RutaCertificado, RutaLlavePrivada, ClaveLlavePrivada: string;
  Reintentar: Boolean;

Const
  _URL_ECODEX_PRUEBAS_V33 = 'https://wsdev.ecodex.com.mx:2045';
  _NUEMRO_TRANSACCION_INICIAL = 1;

begin
  CoInitialize(Nil);
    Try
      Try
        // El primer sello es para Ecodex
        rutaCertificado   := ExtractFilePath(Application.ExeName) + '..\CSD Pruebas\CSD_Pruebas_CFDI_VOC990129I26.cer';
        rutaLlavePrivada  := ExtractFilePath(Application.ExeName) + '..\CSD Pruebas\CSD_Pruebas_CFDI_VOC990129I26.key';

        OpenSSL:= TOpenSSL.Create;
        OpenSSL.AsignarLlavePrivada(rutaLlavePrivada, claveLlavePrivada);

        CertificadoSellos:= TCertificadoDeSellos.Create;
        CertificadoSellos.Leer(rutaCertificado);

        // Verificando certificado de sellos y llave privada... sean pareja
        IF Not openSSL.SonPareja(RutaCertificado, RutaLlavePrivada, ClaveLlavePrivada) Then
        Begin
         Application.MessageBox('Los Archivos de Certificado y Llave Privada No Son Pareja. Favor de Verificar','Certificado SAT SCAMi Recaudación',mb_Ok+mb_iconInformation);
         Exit;
        End;

        //Writeln('Creando instancia de PAC...'); // Configuramos al PAC con los datos para pruebas
        pac := TProveedorEcodex.Create;
        credencialesPAC.RFC            := 'VOC990129I26';
        credencialesPAC.DistribuidorID := '2b3a8764-d586-4543-9b7e-82834443f219';
        // Inicializamos la variable de re-intentar en verdadero para intentar timbrar cada vez que falle el servicio del PAC
        Reintentar:= True;
        While Reintentar Do
        Begin
          Try
            Cancelar_UUID.TEcodexListaCancelar.?
            Cancelar_UUID.RFC = 'BATA761201BY5';
            Cancelar_UUID.Token = ?;
            Cancelar_UUID.TransaccionID = ?;


            // Recibimos el timbre de forma exitosa, dejamos de "reintentar"
            Reintentar := False;

            //Solicitamos el Acuse de Cancelacion del UUID Cancelado
            Solicitar_Acuse.RFC:= ?;
            Solicitar_Acuse.Token:= ?;
            Solicitar_Acuse.TransaccionID:= ?;
            Solicitar_Acuse.UUID:= '';

            //Recuperamos el Acuse de Cancelacion y lo mandamos a Imprimir
            Recuperar_Acuse.AcuseXML;
            Recuperar_Acuse.Estatus;
            Recuperar_Acuse.TransaccionID;
            // Pregunta se deben de Almacenar en Algunas Variables para poder generar la Impresion ???

          except
            On E: EPACErrorGenericoException do
            begin
              Writeln('--------------------------------------------------');
              Writeln('Problema Temporal al Timbrar, Re-Intentando en 3 segundos: ', E.Message);
              Sleep(3000);
            end;
          end;
        end;
    Except
        On E: Exception Do
        Begin
         Application.MessageBox(PChar('** Ocurrio un error inesperado:' + E.ClassName + ': ' + E.Message),'Cancelar CFDi',mb_Ok+mb_iconInformation);
         Exit
        End;
      End;
    Finally
      CoInitialize(Nil);
    End;
 End;
 end;

**Comment by lcarrasco** [comment]
Hola @thinkerbadal te invito a que revises la Guía de Integración de Ecodex:
https://es.scribd.com/document/188415356/Guia-de-Integracion-Con-ECODEX-v2-0-1

Como sabes ahorita todos traemos mucho trabajo con la migración a CFDI 3.3 por lo que solo puedo ayudarte en oportunidades y con preguntas específicas donde ya hayas intentado avanzar.

**Comment by thinkerbadal** [comment]
Saludos voy a colocar el avance la opcion para **CANCELAR** y obtener el **ACUSE DE CANCELACION** del **CFDI**
Alguien que me aporte al CODE por que no logro cancelar

uses  Facturacion.Comprobante, Facturacion.ProveedorAutorizadoCertificacion,
     Facturacion.OpenSSL, Facturacion.CertificadoDeSellos, Facturacion.PAC.Ecodex;

Var
  // Instancias comunes independientes de la version
  OpenSSL : IOpenSSL;
  Pac: IProveedorAutorizadoCertificacion;
  CertificadoSellos: ICertificadoDeSellos;
  CredencialesPAC : TFacturacionCredencialesPAC;
  //Variables
  RutaCertificado, RutaLlavePrivada, ClaveLlavePrivada: String;

Const
  _URL_ECODEX_PRUEBAS_V33 = 'https://wsdev.ecodex.com.mx:2045';

Begin
  Try
          // El primer sello es para Ecodex
          RutaCertificado  := ExtractFilePath(Application.ExeName) + 'CSD_SAT\CSD_Pruebas_CFDI_VOC990129I26.cer';
          RutaLlavePrivada := ExtractFilePath(Application.ExeName) + 'CSD_SAT\CSD_Pruebas_CFDI_VOC990129I26.key';
          ClaveLlavePrivada:= '12345678a';

          OpenSSL:= TOpenSSL.Create;
          OpenSSL.AsignarLlavePrivada(rutaLlavePrivada, claveLlavePrivada);

          CertificadoSellos:= TCertificadoDeSellos.Create;
          CertificadoSellos.Leer(rutaCertificado);

          IF Not openSSL.SonPareja(RutaCertificado, RutaLlavePrivada, ClaveLlavePrivada) Then // Verificando certificado de sellos y llave privada... sean pareja
          Begin
           Application.MessageBox('Los Archivos de Certificado y Llave Privada No Son Pareja. Favor de Verificar','Certificado SAT SCAMi Recaudación',mb_Ok+mb_iconInformation);
           Exit;
          End;

          Pac:= TProveedorEcodex.Create; //Writeln('Creando instancia de PAC...');
          CredencialesPAC.RFC           := 'VOC990129I26';
          CredencialesPAC.DistribuidorID:= '2b3a8764-d586-4543-9b7e-82834443f219';

          IF Pac.CancelarDocumento('02550709-1653-4553-B698-448B5CDD784B') Then
          Begin
           With UniQ_Operations Do
           Begin
            Close;
            SQL.Clear;
            SQL.Add('UPDATE ING_RECIBOS');
            SQL.Add('SET C_CANCEL = ''' + Trim(UpperCase(Causa.Text)) + ''', ');
            SQL.Add('FE_ACUSE_CFDI = ''' + Pac.ObtenerAcuseDeCancelacion('02550709-1653-4553-B698-448B5CDD784B') + ''', ');
            SQL.Add('STATUS = ''CA'''+', ');
            SQL.Add('PC_UPDATE = ''' + Terminal + ''' ');
            SQL.Add('WHERE EJERCICIO = ' + UniQ_Ejercicio.FieldByName('EJERCICIO').AsString + '');
            SQL.Add('AND FOLIO = ''' + UniQ_Ingresos.FieldByName('FOLIO').AsString + '''');
            ExecSQL;
           End;
           UniTransactionWrite.CommitRetaining;
          End
          Else
           Application.MessageBox('El CFDI Seleccionado no puede ser cancelado correctamente, Verificarlo','CANCELACION CFDI',mb_Ok+mb_iconInformation);
      Except
        On E: Exception Do
        Begin
         Application.MessageBox(PChar('** Ocurrio un error inesperado:' + E.ClassName + ': ' + E.Message),'Cancelacion CFDI.',mb_Ok+mb_iconInformation);
         UniTransactionWrite.RollbackRetaining;
         Btn_CancelarClick(Sender);
        End;
      End;
End;

Espero su aportaciones. . .**gracias**

**Comment by lcarrasco** [comment]
Hola @thinkerbadal apenas tuve oportunidad de checar tu caso. Como sabes con cada PAC es diferente la implementación, nosotros usamos Ecodex y asumo tu también, para poder cancelar con Ecodex es necesario que cada emisor / cliente que tengas haya cargado sus certificados de sellos en la plataforma de ellos, esto lo haces entrando a tu Integradex y posteriormente buscando el emisor que desees que canceles, luego hacer clic en "Certificados" y finalmente en el botón "Generar token para carga de certificado".

Una vez hecho esto el emisor podrá mandar cancelar con la siguiente función:

```pascal
// NOTA: Debes tener previamente creada y configurada la instancia de pacEcodex
// Aqui pasamos como parámetro el UUID de la factura a cancelar
try
   if pacEcodex.CancelarDocumento('4a1b43e2-1183-4ad4-a3de-c2da787ae56a') then
       ShowMessage('Cancelación Exitosa');
except
   on E:Exception do
        ShowMessage('Falló la cancelación, mensaje:' + E.Message);
end;
```

Para obtener el acuse necesita haber pasado al menos 24 horas pues es el tiempo promedio que tarda el SAT en proveer de dicha información al PAC. Una vez pasado este tiempo puedes solicitar el acuse así:

```pascal
acuseXML := pacEcodex. ObtenerAcuseDeCancelacion('4a1b43e2-1183-4ad4-a3de-c2da787ae56a');
```

Si tienes cualquier problema con la plataforma de Integradex recuerda que Ecodex también te puede y debe darte soporte, usualmente responden en su correo soporte@ecodex.com.mx
