### ISSUE TITLE
Que otro parametro recibe esta marcando error

### ISSUE THREAD

**Issue by thinkerbadal** [bambucode/tfacturaelectronica#120]
si el pac es ecodex
          if nuevaFactura.Version = '3.3' then
            pac.Configurar(_URL_ECODEX_PRUEBAS_V33,
                         credencialesPAC,
                         _NUEMRO_TRANSACCION_INICIAL)
          else
            pac.Configurar(_URL_ECODEX_PRUEBAS_V32,
                           credencialesPAC,
                           _NUEMRO_TRANSACCION_INICIAL);

**[dcc32 Error] EjemploFacturaElectronica.dpr(386): E2010 Incompatible types: 'TFacturacionCredencialesPAC' and 'Integer'**

Facturacion.ProveedorAutorizadoCertificacion

procedure Configurar(const aDominioWebService: string; const aCredencialesPAC,
        aCredencialesIntegrador: TFacturacionCredencialesPAC; const
        aTransaccionInicial: Int64);

**Comment by epadillac** [comment]
Hola @thinkerbadal, Ya quedó corregido en el último commit (https://github.com/bambucode/tfacturaelectronica/commit/caa83adfcc715b8a14a75c01a1456e409cbe4a4f)

**Comment by thinkerbadal** [comment]
excelente gracias
