### ISSUE TITLE
Se agregó pull request para agregar comaptibilidad con delphi 7 y delphi XE1

### ISSUE THREAD

**Issue by fduenas** [bambucode/tfacturaelectronica#144]
Hola solo para mencionarles que he hecho un Pull request el cual agrega compatibilidad con Delphi 7 y XE1: https://github.com/fduenas/tfacturaelectronica/tree/fadr-compatibilidad-xe1-d7

-  Se agregó y probó exitósamente el soporte con Delphi 7, Delphi XE1 y Delphi XE 10.2.3 (Tokyo), por lo cual no debe haber problema con Delphi 2009 y 2010 y demás versiones intermedias.

-  Para el soporte con Delphi 7, Delphi 2007, Delphi 2009 y Delphi 2010 se requiere usar la librería TPerlRegExp para el uso de Expresiones Regulares.
	- Esta puede descargarse desde la página: <https://www.regular-expressions.info/delphi.html>
     o directamente desde: <https://www.regular-expressions.info/download/TPerlRegEx.zip>
	- También se conserva una copia de dicha librería desde el repositorio: <https://github.com/fduenas/TPerlRegEx>
	- Una vez descargado el archivo, extraerlo en la carpeta de su conveniencia 
	- Agregar el folder que contiene los archivos a la configuracion Library Path del Delphi: Tools/Environment Options/Library/Library path
	
	- Para Mayor información acerca del uso de esta librería consultar: https://www.regular-expressions.info/delphi.html

Para más información consultar el Pull request:  fadr-compatibilidad-xe1-d7 https://github.com/bambucode/tfacturaelectronica/pull/143

Espero sus comentarios

**Comment by lcarrasco** [comment]
Este PR ya fue integrado, muchas gracias @fduenas !
