### ISSUE TITLE
Nuevo CFDI v 4.0

### ISSUE THREAD

**Issue by FLugo65** [bambucode/tfacturaelectronica#164]
Hola, alguien ya comenzó a trabajar/probar con el nuevo esquema para el CFDI v 4.0?

**Comment by lcarrasco** [comment]
Hola @FLugo65 aunque aun no hay información oficial por parte del SAT (Anexo 20, fechas, etc). Hay cierta información que ya nos envió nuestro PAC en privado y la estamos analizando.

**Comment by FLugo65** [comment]
Gracias Luis, de igual manera empezaré a analizar la informacion que mi PAC
nos está enviando. En mi caso es FinkOk.

Me quedo con la idea de que con el diseño de la última versión de la
utilería, habrá que actualizar con los nuevos esquemas que nos ofrezca el
SAT e identificar los nuevos nodos obligatorios que deberemos procurar en
nuestras aplicaciones para llenar el XML, ¿voy bien?

Saludos cordiales,

Felipe Lugo

**Comment by lcarrasco** [comment]
> Me quedo con la idea de que con el diseño de la última versión de la
utilería, habrá que actualizar con los nuevos esquemas que nos ofrezca el
SAT e identificar los nuevos nodos obligatorios que deberemos procurar en
nuestras aplicaciones para llenar el XML, ¿voy bien?

Asi es Felipe. En teoría no debe ser tan complicado implementar la nueva versión...

Saludos

**Comment by lcarrasco** [comment]
Buen dia, se tiene avance parcial en el siguiente pull request:
https://github.com/bambucode/tfacturaelectronica/pull/166

Quien guste colaborar, experimentar, etc bienvenido.

**Comment by FLugo65** [comment]
Buen dia Luis, yo trabajo con FinkOk, como puedo ir haciendo pruebas en
paralelo a tu Pack con lo que vas avanzando?

Saludos,

FLugo

**Comment by lcarrasco** [comment]
## Actualización:

Creo que la librería ya esta "lista" respecto a los cambios que debe tener en su mayoría, sin embargo desde la semana pasada me encuentro bloqueado ya que los ejemplos que faltan de timbrar: factura global, factura público en general, factura a extranjero aún no timbran con mi proveedor (Ecodex) a lo que yo le atribuyo errores del proveedor que aun están corrigiendo y que de momento su plataforma no está lista.

Si alguien logra timbrar dichos ejemplos ya sea con Ecodex u otro PAC favor de comentarlo para al menos saber que ya no es problema de la librería.

De nuestra parte seguiremos probando ocasionalmente para ver cuando Ecodex realiza las correcciones pertinentes.

**Comment by FLugo65** [comment]
Gracias Luis, hoy empiezo pruebas, no lo había podido hacer antes porque no
entendía la mecánica de trabajo de la plataforma
GitHub y por lo tanto no había podido bajar las versiones de avance que
publicabas.

Te mantendré informado de mis avances en las pruebas con FinkOk

Felipe Lugo

**Comment by FLugo65** [comment]
Luis qué versión de Delphi estás usando? Me marca error en una
clase: [dcc32 Error] Facturacion.PAC.Ecodex.pas(56): E2003 Undeclared
identifier: 'TSOAPHttpErrorAction'

Yo uso Delphy 10.2 Tokyo

Saludos

**Comment by lcarrasco** [comment]
Hola @FLugo65 no vi tu mensaje. Estamos usando Delphi 10.3 Seattle de momento.

**Comment by lcarrasco** [comment]
## Actualización:

El dia de hoy se probaron los distintos escenarios con el proyecto de ejemplo logrando timbrar con el PAC de forma exitosa los escenarios de:

* Factura CFDI 4.0 con receptor de público en general.
* Factura CFDI 4.0 con receptor extranjero.
* Factura CFDI 4.0 con receptor normal.
* Factura CFDI 4.0 con ventas e impuestos de Franja Fronteriza.
* Factura CFDI 4.0 global.
* Factura CFDI 4.0 con complemento de pago.

Con este anuncio se comienza en una etapa beta de la librería.

**Comment by FLugo65** [comment]
Buen dia mi estimado, para comentarte que ya hice mi primer timbrado de
prueba versión CFDI 4.0 con el PAC FinkOk.

Continuo con las pruebas y te comento.

Adjunto una XML de prueba.

Saludos cordiales,

FLugo

**Comment by FLugo65** [comment]
Problema de compatibilidad Delphi 10.2 Tokio:

Para comentarte que me marca error con esta librería que según yo, solo se
requiere cuando trabajas con Ecodex. Para poder hacer mis pruebas elimine
toda referencia a los otros PACs distintos a FinkOK.

Te paso imagen del error:

[image: image.png]

También tengo problemas con el Generador de Código de Barras Bidireccional.

Saludos,

FLugo

**Comment by lcarrasco** [comment]
Hola @FLugo65 creo que como respondiste via correo no se están anexando las imágenes o adjuntos a la conversación. Si gustas hacerlo directamente desde GitHub:
https://github.com/bambucode/tfacturaelectronica/issues/164

**Comment by Opsmc** [comment]
Hola, soy nuevo acá en este foro. Bajé el ejemplo, pero al momento de compilar el ejemplo con RAD Studio 10.4 obtengo el siguiente error
<img width="533" alt="Error" src="https://user-images.githubusercontent.com/19996592/175644307-753d1d30-9378-4a8b-81de-ba9742acb175.png">


Gracias por el apoyo

**Comment by FLugo65** [comment]
Hola  yo uso el PAC FinkOk y Delphi 10.2 y 10.4 con los dos no tengo
problemas con la libreria. Al principio si tube problemas precisamente con
ese PAC, lo que hice fue eliminar todas las referencias del resto de los
Pacs que no uso y santo remedio.

Espero y te sirva de algo mi retroalimentacion.

FLugo
