### ISSUE TITLE
AutoIndent

### ISSUE THREAD

**Issue by jalin** [bambucode/tfacturaelectronica#19]
La librería como esta genera el archivo XML en una sola linea, me imagino que seria bueno que cada nodo lo vaya indentando (?sangrando?). Modifique la unidad COMPROBANTEFISCAL en la linea 219 y lo deje como:

  fDocumentoXML := TXMLDocument.Create(nil);
  fDocumentoXML.NodeIndentStr:='  ';
  fDocumentoXML.Options:= fDocumentoXML.Options+[doNodeAutoIndent];

(a veces la ultima linea la escribo fDocumentoXML.Options:= [doNodeAutoIndent];)

pero ahora que lo ejecuto me manda el error:

EIntFCastError: Interface not supported.

Que estoy haciendo mal? si hago una prueba creando un programa de cero y una instancia de TXMLDocument tal como lo puse arriba y lo ejecuto no me da problemas. y el XML que genero si lo deja con la sangría.

Saludos

**Comment by lcarrasco** [comment]
Se cierra Issue por falta de seguimiento / obsoleto.
