### ISSUE TITLE
No es posible usar Cuenta Predial en los conceptos.

### ISSUE THREAD

**Issue by thinkerbadal** [bambucode/tfacturaelectronica#33]
SALUDOS

ESTOY USANDO LA LIBRERIA PARA GENERAR EL CFDI

Y ME MARCA ERROR CUANTO LE ANEXO EL NUMERO DE CUENTA PREDIAL:

// Definimos todos los conceptos que incluye el Recibo Detalle
         Try
           UniQ_RD.DisableControls;
           UniQ_RD.Open; UniQ_RD.First;
           While Not(UniQ_RD.Eof) Do
           Begin
            Concepto.CuentaPredial:= Cuenta.Text;
            Concepto.NoIdentificacion:= UniQ_RD.FieldByName('CUENTA').AsString;
            Concepto.Cantidad:= UniQ_RD.FieldByName('CANTIDAD').AsInteger;
            Concepto.Unidad:= 'NO APLICA';
            Concepto.Descripcion:= UniQ_RD.FieldByName('D_CUENTA').AsWideString;
            Concepto.ValorUnitario:= UniQ_RD.FieldByName('COSTO').AsCurrency;
            Factura.AgregarConcepto(Concepto);
            UniQ_RD.Next;
           End;
          Finally
           UniQ_RD.First;
           UniQ_RD.EnableControls; UniQ_RD.Close;
          End; //Fin del ciclo Recibo Detalle

Y ME GENERA ESTO
![06-02-2014 03-00-55 p-m-](https://f.cloud.github.com/assets/6216503/2104118/e9dbfc34-8f76-11e3-8462-fe616809d15e.jpg)

LO MAS CURIOSO ES QUE PONGO EN COMENTARIO LA LINEA Y SI ME GENERA EL CFDI

//Concepto.CuentaPredial:= Cuenta.Text;

**Comment by lcarrasco** [comment]
En la nueva versión (https://github.com/bambucode/tfacturaelectronica/pull/82) se tiene soporte nativo usando la interfase para manejar todos los nodos incluyendo la cuenta predial.
