### ISSUE TITLE
Anexar a la Libreria lo siguiente es importante:

### ISSUE THREAD

**Issue by thinkerbadal** [bambucode/tfacturaelectronica#42]
SALUDOS
Estoy usando su libreria para generar facturas electronicas, funciona muy bien con el PAC's Ecodex, solo tengo dos detalles que ya son observables por los contadores, que la libreria actualmente no genera o anexa al XML la SERIE y la CUENTA PREDIAL

Agradeceria que le den solucion a esta peticion.. . .gracias

Nota: no soy experto en modificar su libreria, solo soy un usuario final mas, que les da las gracias por haber desarrollado su libreria y que funciona excelente asta el momento.

anexo ejemplo de un XML donde se aprecia la SERIE y la CUENTA predial
![serie_y_cuenta_predial_en_xml](https://cloud.githubusercontent.com/assets/6216503/6565900/67d453a4-c679-11e4-8072-a799e8721701.jpg)

**Comment by lcarrasco** [comment]
Se cierra al ser duplicado de #33
