### ISSUE TITLE
Nuevo Certificado SHA256

### ISSUE THREAD

**Issue by pimentelflores** [bambucode/tfacturaelectronica#49]
Saludos a todos., una pregunta, se han enfrentado con el nuevo certificado del sat SHA256? que empezaron a emitir a partir de mayo 2015, (tal vez antes), 
se han topado con que al parecer la implementacion para hacer la digestion ya no funciona mas ya que se usa sha1?.. 
me podrian orientar para hacer la implementacion con sha256?

**Comment by lcarrasco** [comment]
Hola, según yo, esto ya está corregido en master, aquí los detalles del Pull Request donde fue corregido:

https://github.com/bambucode/tfacturaelectronica/pull/48

¿Ya probaste con la version mas reciente? ¿Presentas alguna falla?

**Comment by pimentelflores** [comment]
Muchisimas Gracias, en verdad busque si habia una actualizacion y no la encontre, gracias por la ayuda, quedo perfecto 
Saludos.

**Comment by lcarrasco** [comment]
:+1:
