### ISSUE TITLE
Manejar nuevo catálogo de métodos de pago (al 3 de Junio 2016)

### ISSUE THREAD

**Issue by lcarrasco** [bambucode/tfacturaelectronica#63]
![captura de pantalla 2016-06-03 a las 4 35 04 p m](https://cloud.githubusercontent.com/assets/127025/15839841/1eea1a70-2c03-11e6-93ea-f4b3b2e5695f.png)

**Comment by luishoracio-bambucode** [comment]
Done en el #73
