### ISSUE TITLE
Como asigno una moneda diferente al peso

### ISSUE THREAD

**Issue by Opsmc** [bambucode/tfacturaelectronica#64]
Hola, antes que nada les agradezco tan maravilloso aporte. 

Hay algún ejemplo en donde se asigne un tipo de moneda diferente al peso. Es específico Dólares :D

**Comment by lcarrasco** [comment]
@Opsmc En la versión actual aun no hay soporte, pero en los cambios hechos por @ptorres del pull request #65 ya es posible. Nos encontramos en revisión, estás invitado a colaborar si gustas :)

**Comment by ptorres** [comment]
Me encantaría apoyar ahora pero ando manejando. Una disculpa por eso. 

Enviado desde mi iPhone

**Comment by Opsmc** [comment]
Con mucho gusto les colaboro en lo que guste. Me pongo a su disposición.

 

Por cierto hice unos cambios para poder facturar con diferente tipo de monedas. 

 

 

Saludos

 

 



Este correo electrónico y la información que contiene son confidenciales y pueden ser privilegiados, si Usted ha recibido este mensaje por error, por favor notifíquelo inmediatamente. Usted no debe copiar este correo para cualquier propósito, o divulgar su contenido a ninguna otra persona. En cumplimiento a la Ley Federal de Protección de Datos Personales en Posesión de Particulares, y su reglamento, nuestro aviso de privacidad se encuentra disponible en http://www.farrera-it.com/aviso_privacidad.html. Usted como titular de datos personales, al responder a este comunicado, acepta y manifiesta el conocer nuestro aviso de privacidad, otorgando por tal motivo su consentimiento de manera libre, informada y especifica al tratamiento de sus datos personales, lo anterior de conformidad a nuestro aviso de privacidad.

This email and the information it contains are confidential and may be privileged, if you have received this email in error please notify us immediately. You should not copy it for any purpose, or disclose its contents to any other person.
In accordance to the dispositions of the Federal Law for Protection of Personal Data in Possession of Particulars, and its guidelines, our Privacy Notice is available on our website  <http://www.farrera-it.com/aviso_privacidad.html> http:www.farrera-it.com/aviso_privacidad.html. As the title holder and barer of Personal Data owner, by replying to this message you are acknowledging and accepting in a free, informed and specific manner the terms of our privacy notice and the treatment that we will execute regarding your personal information.

 

De: Luis Carrasco [mailto:notifications@github.com] 
Enviado el: sábado, 18 de junio de 2016 01:50 p. m.
Para: bambucode/tfacturaelectronica <tfacturaelectronica@noreply.github.com>
CC: Opsmc <mariocrf@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [bambucode/tfacturaelectronica] Como asigno una moneda diferente al peso (#64)

 

@Opsmc <https://github.com/Opsmc>  En la versión actual aun no hay soporte, pero en los cambios hechos por @ptorres <https://github.com/ptorres>  del pull request #65 <https://github.com/bambucode/tfacturaelectronica/pull/65>  ya es posible. Nos encontramos en revisión, estás invitado a colaborar si gustas :)

**Comment by lcarrasco** [comment]
En la nueva versión (https://github.com/bambucode/tfacturaelectronica/pull/82) se tiene soporte nativo usando la interfase para manejar todos los nodos incluyendo el de moneda.
