### ISSUE TITLE
Biblioteca para Delphi 2007

### ISSUE THREAD

**Issue by ffaccinetto** [bambucode/tfacturaelectronica#78]
Hola buenas tardes.

Estoy tratando de implementar su biblioteca en Delphi 2007 Enterprise, sin embargo me manda varios problemas con bibliotecas que aparentemente son de versiones mas nuevas de Delphi.

¿Conservan alguna versión de su código que sea compatible con Delphi 2007?

**Comment by ffaccinetto** [comment]
O en su caso, alguien que la pueda tener para Delphi 7.

**Comment by ffaccinetto** [comment]
Disculpen la molestia, pero no puedo hacer que funcione su biblioteca en Delphi 2007, me manda demasiados errores con esta versión de Delphi porque llama funciones y clases que solamente existen en versiones posteriores.

¿Me puede ayudar a obtener una versión que sea compatible con Delphi 2007?

Saludos

**Comment by mr-E** [comment]
"Huyendo" de la librería de aquel foro eh? (reconocí tu nickname).
En este momento no tengo D7 instalado, podrías poner los mensajes de error que te salen? (con suerte aun tengo el proyecto que me compilo, tratare de buscarlo)
Hace unas semanas la compile en Seattle/Berlin con pocos ajustes.
Este proyecto tiene una comunidad en: https://groups.google.com/forum/#!forum/tfacturaelectronica.

**Comment by ffaccinetto** [comment]
Si, así es, resulta que en ValidaCFD, a Dado se le ocurrió que para usar su biblioteca, debemos timbrar con su PAC, el cual creo es ECODEX o algo asi, ¿Que te parece?

La verdad, es que en su momento nos saco del apuro para la implementación del CFDI en nuestro sistema, pero ahora con esa nueva regla....pues nos vino a perjudicar, dado que los usuarios de nuestro sistema trabajan con diferentes PAC, como Solución Factible, Edicom y Facturas Inteligentes, para los cuales ya desarrolle el código delphi para utilizar sus WebServices en base a las DLL que ellos proporcionan.

Por lo que, realmente lo que nosotros necesitamos es solamente generar el XML con todos los requisitos del SAT para su timbrado.

Te agradezco tu ofrecimiento y te estaré enviando los problemas que me reporta al compilar con Delphi 2007, y de antemano te agradezco tu apoyo.

Saludos

**Comment by ffaccinetto** [comment]
Por ejemplo, en la unidad ComprobanteFiscal, en los Uses, tenemos lo siguiente:

uses FacturaTipos, SysUtils,
  // Unidades especificas de manejo de XML:
  {$IF Compilerversion >= 20}
  Xml.xmldom,
  Xml.XMLIntf,
  Xml.Win.MsXmlDom,
  Xml.XMLDoc,
  {$ELSE}
  XmlDom, XMLIntf, Xml.win.MsXmlDom, XMLDoc,
  {$ENDIF}
  DocComprobanteFiscal, FeCFDv22,FeCFDv32, FeCFDv2, feCFD;

Y el error que señala es el siguiente:

[DCC Error] ComprobanteFiscal.pas(29): F1026 File not found: 'Xml.win.MsXmlDom.dcu'

Para que no me mande ningún error de compilación, debo dejarla como sigue:

uses FacturaTipos, SysUtils,
  XmlDom, XMLIntf, MsXmlDom, XMLDoc,
  DocComprobanteFiscal, FeCFDv22,FeCFDv32, FeCFDv2, feCFD;

Y compila bien la unidad.

**Comment by luishoracio-bambucode** [comment]
@ffaccinetto revisa los cambios de este merge : https://github.com/bambucode/tfacturaelectronica/pull/57/commits/b89c5746d61e843b1fd9ba2e11be4cb7679f50d6

**Comment by ffaccinetto** [comment]
En la unidad FacturaReglamentacion, en la función ConvertirNumeroMetodoDePagoACadena, en la declaracion de variables, presenta el siguiente problema:

auxArrayMetodos  : TArray<string>;

Reporta el siguiente problema:

[DCC Error] FacturaReglamentacion.pas(272): E2003 Undeclared identifier: 'TArray'

La cual se puede resolver de la siguiente manera, según yo:

**Comment by ffaccinetto** [comment]
En la unidad FacturaReglamentacion, en la función ConvertirNumeroMetodoDePagoACadena, al declarar la variable auxArrayMetodos, utiliza la clase TArray, la cual en Delphi 2007 no existe, eso lo resolvi de la siguiente manera:

  {$IF Compilerversion >= 20}
   auxArrayMetodos  : TArray<string>;
  {$ELSE}
   auxArrayMetodos  : Array of string;
  {$IFEND}

Sin embargo, se presenta en siguiente problema:

auxArrayMetodos := aNumeroMetodoDePago.Split([',']);

En donde la función Split, no existe. ¿Tengo que hacer mi propia funcion de Split?, que opinas?

Saludos

**Comment by lcarrasco** [comment]
@ffaccinetto Creo que si será necesario que crees tu propia función split en Delphi 2007.

**Comment by ffaccinetto** [comment]
Hola, alguna idea de la clase TMach,  TMatchCollection y TRegEx?

**Comment by ptorres** [comment]
Hola @ffaccinetto no se si me pudieras facilitar tu correo para pasarte la libreria funcionando con D2007.
saludos

**Comment by ffaccinetto** [comment]
Si claro, con mucho gusto: 

ffaccinetto@aptus-legal.com

Muchas Gracias

**Comment by lcarrasco** [comment]
@ptorres Puedes subirla mientras por ZIP aqui para futuros visitantes en lo que hacemos el merge correspondiente. ¿Como vez?

**Comment by ffaccinetto** [comment]
Si claro, con mucho gusto, yo la prueba en Delphi 2007, y luego la subo, para comprobar que todo funcione bien.

**Comment by lcarrasco** [comment]
:+1:

**Comment by ffaccinetto** [comment]
mi otro correo es ffaccinetto@gmail.com

**Comment by ptorres** [comment]
Ok aqui la subo.
Saludos.
[tfacturaelectronica.zip](https://github.com/bambucode/tfacturaelectronica/files/613777/tfacturaelectronica.zip)

**Comment by ffaccinetto** [comment]
Les agradezco mucho, yo inicio las pruebas y les mantengo informados de los resultados.

Saludos

**Comment by ffaccinetto** [comment]
Tienen la unidad PerlRegEx, no esta contenida en la información enviada.

**Comment by ffaccinetto** [comment]
Ya descargue la biblioteca "Download the older component-based TPerlRegEx" de la siguiente liga:

http://www.regular-expressions.info/delphi.html

Y compilo el ejemplo que estoy haciendo.

Saludos

**Comment by ptorres** [comment]
Perfecto saludos

**Comment by ffaccinetto** [comment]
Al compilar el EjemploFacturaElectronica, me solicita la funcion EncodeBase64, ya la busque en los programas proporcionados, pero no la encuentro. Me pueden ayudar?

Saludos

**Comment by ptorres** [comment]
Estas compilando en D2007? o 7

**Comment by ffaccinetto** [comment]
Delphi 2007

**Comment by ptorres** [comment]
Si trae aplicada la actualización, December 2007 Update?

**Comment by ffaccinetto** [comment]
Si, tengo instalado hasta CodeGear RAD Studio 2007 Update 3

**Comment by ptorres** [comment]
Ya lo revise la función pertenece a Synapse [http://www.ararat.cz/synapse/](url)

**Comment by ffaccinetto** [comment]
OK, déjame verificar la biblioteca y en su caso ponerla en mi Delphi 2007.

Saludos.

**Comment by ffaccinetto** [comment]
Listo, descargue la biblioteca, la instale y ya se compilo el ejemplo.

Seguiré haciendo pruebas y los mantengo informados.

Nota:  En la unidad GeneradorCBB, movi la referencia a la unidad pngimage dentro del $IF para versiones mayores o iguales a 20, dado que para Delphi 2007 no existe esta unidad.

Saludos

**Comment by ffaccinetto** [comment]
Hola, ya compile un nuevo ejemplo que estoy haciendo, pero no funciona.

Simplemente cree una VCL Forms Application - Delphi for Win 32, puse un botón y dentro del evento OnClick del botón puse el código para crear la factura de ejemplo. 

Sin embargo cuando ejecuto la aplicación creada, simplemente hace un pantallazo y me regresa al IDE del Delphi. Si comento el siguiente código:

Factura := TFacturaElectronica.Create(Emisor, Receptor, Certificado, tcIngreso);

Entonces si la aplicación funciona correctamente, pero obviamente no puedo probar la creación de la factura. ¿Alguna idea de porque se presenta este comportamiento?

Les envió el código  fuente con el que estoy probando, algo estoy haciendo mal pero no logro descubrirlo.

Saludos

[FUENTES_PRUEBAS.zip](https://github.com/bambucode/tfacturaelectronica/files/613860/FUENTES_PRUEBAS.zip)

**Comment by ptorres** [comment]
si estas poniendo la librería pcrelib.dll ?

**Comment by ffaccinetto** [comment]
No, tienes toda la razón, el problema era ese, ya la puse y funciono bien. 

Tache para mi, olvide copiar esa DLL en mi proyecto.

Gracias

Saludos

**Comment by ptorres** [comment]
saludos.

**Comment by ffaccinetto** [comment]
;-) Perfecto, ya pude generar mi primer CFDI sin timbrar y todo funciono bien, continuare haciendo pruebas  , ya dentro de mi aplicación y después trabajare en la integración de los PAC que utilizamos.

Muchas Gracias por su apoyo y los seguiré informando.

Saludos

**Comment by ptorres** [comment]
Perfecto, si pudieras compartir una vez que tengas la integración con los otros PAC se agradeceria.

**Comment by ffaccinetto** [comment]
Me parece correcto, asi lo hare.

Ya si me surgen dudas sobre la implementación, recurriré a ustedes para dejarla lo mas estándar posible.

Saludos

**Comment by ffaccinetto** [comment]
Hola, buenas tardes.

Ya estoy trabajando en la creación de la programación para el PAC Solución Factible, sin embargo debo reconocer que mi experiencia con el manejo de los WebServices por medio del SOAP es nula, me podrían ayudarme (orientarme) en como hacer la o las clase para explotar el WS del PAC.

Anexo les envió mi avance, como referencia. Entre ellos el archivo PAS creado de la importación del WSDL del PAC.

Saludos

[PACSolucionFactible.zip](https://github.com/bambucode/tfacturaelectronica/files/614496/PACSolucionFactible.zip)

**Comment by ffaccinetto** [comment]
Les comento que intente hacerlo como el PAC Comercio Digital, y obviamente no funciono correctamente.

Saludos

**Comment by ffaccinetto** [comment]
Hola buenas tardes.
Una duda. ¿En las versiones mas recientes de la biblioteca, están manejando diversas formas de pago?

Saludos

**Comment by lcarrasco** [comment]
@ffaccinetto Siempre se ha soportado establecer el valor deseado en la propiedad `MetodoDePago`. En la versión mas reciente se "traduce" automáticamente `Efectivo` por `01` en el XML para cumplir con la ultima normativa.

Más detalles en: https://github.com/bambucode/tfacturaelectronica/issues/63

**Comment by ffaccinetto** [comment]
Hola, buenas noches.

Les informo que ya termine la parte de generación de los XML, para lo cual cree los métodos AsignarMoneda y AsignarTipodeCambio, en la unidad ComprobanteFiscal.

Por otro lado, debido a que la versión de FastReport que utilizo para generar PDF de los CFDI solamente maneja imágenes de tipo BMP, cree el método GenerarImagenBMP en la unidad GeneradorCBB, la cual crea el CBB en un archivo BMP.

También en la función AsignarMetodoDePago de la unidad ComprobanteFiscal, agregue una validación para que cuando el usuario mande varios métodos de pago (por ejemplo: 03,01) lo reconozco la función y la asigne al método de pago.

Si gustan, les puedo hacer llegar el código fuente como lo tengo, para su revisión, comentarios y estandarización.

Por otra parte, como les comente en comentarios anteriores, ahora modificare la biblioteca para integrar el WebService del PAC Solución Factible, para lo cual no tengo fecha, dado que mis conocimientos al respecto del uso de SOAP son prácticamente nulos.

Quedo a sus ordenes y en espera de sus comentarios.

Saludos.

**Comment by lcarrasco** [comment]
Buenos dias, excelente @ffaccinetto te agradecería mucho compartieras tu código. Si gustas puedes [mandarnos un pull request](http://www.cristalab.com/tutoriales/como-colaborar-en-un-proyecto-en-github-c112327l/) para integrar tus cambios.

Saludos

**Comment by ffaccinetto** [comment]
Según la liga que me enviaste, cree un Fork de la biblioteca y es ahí donde estaré actualizando los cambios realizados.

https://github.com/ffaccinetto/tfacturaelectronica

Es esto correcto?

Saludos

**Comment by lcarrasco** [comment]
Correcto @ffaccinetto

**Comment by ffaccinetto** [comment]
Ya concluí los trabajos de creación de los programas para el PAC Solución Factible, ya los subí en el repositorio.

https://github.com/ffaccinetto/tfacturaelectronica/tree/master/PACs/SolucionFactible

Saludos

**Comment by HubelSB** [comment]
Saludos soy de peru, aqui tambien solicitan facturas electronicas, recien estoy probando esto, la parte de generar los XML, lo habia resuelto en Lazarus, todo en estructurada para migrar entre plataformas sin lio, el firmado mediante la libreria XMLSec2, en el envio tengo problemas con el WSDL, aunque que logrado conectarme con el servicio sigo sin enviar, empezare a revisar su libreria para ver si puedo ayudarme, les dejo el link de la entidad que se hace cargo aca en Peru.

http://orientacion.sunat.gob.pe/index.php/empresas-menu/comprobantes-de-pago-empresas/comprobantes-de-pago-electronicos-empresas/see-desde-los-sistemas-del-contribuyente/2-comprobantes-que-se-pueden-emitir-desde-see-sistemas-del-contribuyente/comprobante-de-retencion-electronico-desde-sistemas-del-contribuyente/3649-rutas-para-pruebas-y-envios

**Comment by ffaccinetto** [comment]
Buenas tardes.

Estoy trabajando con el timbrado con Edicom, la cual ya esta resuelta y probada. Sin embargo para las cancelaciones tengo que manejar los archivos en formato PFX.

Mis preguntas son:

¿Tienen algún procedimiento para crear los archivos PFX a partir del CER y KEY?
¿Y ademas una rutina para realizar la lectura de archivos PFX?

Quedo en espera de sus comentarios.

Saludos

**Comment by ffaccinetto** [comment]
Les comento que ya subi mi avance con el PAC EDICOM, sin embargo la parte de cancelacion de CFDI la tengo detenida hasta que resuelva el punto anterior.

Ya los subí en el repositorio.

https://github.com/ffaccinetto/tfacturaelectronica/tree/master/PACs/Edicom

Saludos

**Comment by lcarrasco** [comment]
Hola @ffaccinetto Respondo tus dudas:

**¿Tienen algún procedimiento para crear los archivos PFX a partir del CER y KEY?**
De momento no, si se tendría que crear un procedimiento para ello si quieres hacerlo de forma nativa. Si gustas busca en el grupo de soporte, creo que alguien ya había solicitado algo así y tenia código de avance.

**¿Y ademas una rutina para realizar la lectura de archivos PFX?**
Igual que la anterior.

Nos va a tomar unos dias revisar tu código ya que traemos mucho trabajo ahorita en la oficina pero si está en los pendientes. Saludos

**Comment by ffaccinetto** [comment]
OK lcarrasco, bienvenidos sus comentarios y sugerencias.

Saludos

**Comment by lcarrasco** [comment]
Hola @ffaccinetto acabo de actualizar la librería para soporte para CFDI 3.3, sin embargo dado que no dispongo de una edición de Delphi 2007 el soporte para dicha versión no existe.

Si gustas puedes colaborar con esa parte, puedes ver los cambios propuestos en: #82

**Comment by jibleg** [comment]
Buenas Tardes,

Tengo la version 3.2 y estoy iniciando la migracion a la version 3.3 en Delpgi 7. Intento compilar sin exito. Me pueden retroalimentar ?

salu2

**Comment by lcarrasco** [comment]
@jibleg La nueva versión de la biblioteca, con soporte para 3.3 aun no tiene soporte para Delphi 7. Ya que solo dispongo de Delphi Seattle se me dificulta probar en otras ediciones. Si gustas puedes ir poniendo los errores que te salen / líneas de código para que yo u otros programadores podamos irte auxiliando en implementar la compatibilidad.

**Comment by ffaccinetto** [comment]
@jibleg No estoy trabajando con Delphi 7,  y para la versión 3.3 lo estoy trabajando en Delphi Tokyo con el desarrollo actual de @lcarrasco.

**Comment by lcarrasco** [comment]
Excelente @ffaccinetto ¿En que estás trabajando? Para evitar repetir trabajo. Recientemente logré implementar el manejo de impuestos locales y por lo que veo sería muy similar para el resto de los complementos.

**Comment by ffaccinetto** [comment]
Ahorita estuve revisando y entendiendo su lógica y el esquema que plantearon, también quiero hacer la interface para el PAC Solución Factible, pero si gustes que trabaje con algún tema en particular no dudes en avisarme y con mucho gusto colaboro con ello, cuenten con mi apoyo.

**Comment by jibleg** [comment]
Enterado @ffaccinetto; yo apenas estoy migrando la solucion de la empresa
de la version D7 a Delphi Berlin y me acabo de enterar por tu medio que
estamos en Tokyo 🙁

**Comment by ffaccinetto** [comment]
@jibleg Yo la estoy trabajando con Tokyo, sin embargo @lcarrasco la esta trabajando en Seattle, como puedes ver, son dos versiones diferentes. En teoría no debes de tener problemas con Berlin. Es importante mencionar que la versión 3.3 maneja un esquema diferente a la versión 3.2, te sugiero le des una revisada al código fuente de la nueva versión para que aprecies las diferencia con la versión anterior. Yo trabajaba con Delphi 2007, pero debido a las limitantes propias de esta versión de Delphi (como sea son 10 años de antigüedad), fue que decidí mejor migrar a la versión mas reciente de Delphi.

**Comment by lcarrasco** [comment]
Gracias @ffaccinetto de momento otros PACs es excelente ayuda al igual que en debuguear pues como viste fue un re-write completo.

**Comment by fduenas** [comment]
Ya se hizo un Pullrequest y se actualizó el branch 'master' solo hace falta que hagn pruebas en Delphi 2007, 2009 y 2010. 

Las pruebas que yo realicé fueron en: Delphi 7, Delphi Xe1 y Delphi 10.2.3 (Tokio), todas existosas, muy importante que vean las Notas de compatifibilidad para Version anteriores a Delphi XE1.

Pienso que ya este hilo debería cerrarse.

**Comment by lcarrasco** [comment]
Muy bien, gracias @fduenas
