### ISSUE TITLE
[DCC Error] FacturaReglamentacion.pas(281)

### ISSUE THREAD

**Issue by thinkerbadal** [bambucode/tfacturaelectronica#79]
saludos, estoy usando la libreria en RAD Studio XE al compilar me esta marcando este Error
![error](https://cloud.githubusercontent.com/assets/6216503/21571247/06bef352-ce93-11e6-9ae2-56bd35ffcf6f.jpg)

[DCC Error] FacturaReglamentacion.pas(281): E2018 Record, object or class type required

alguien ayude. . .espero. . .gracias

**Comment by thinkerbadal** [comment]
RAD Studio XE

uses DateUtils,
     {$IF Compilerversion >= 23}
     Soap.XSBuiltIns,
     {$ELSE}
     XSBuiltIns,
     {$IFEND}
     SysUtils, StrUtils, Types, Windows;

class function TFEReglamentacion.ConvertirNumeroMetodoDePagoACadena(const aNumeroMetodoDePago: string): String;
var
  auxRespuesta : string;
  auxArrayMetodos  : TStringDynArray; //TArray<string>;
begin
. . .
 auxArrayMetodos := SplitString(aNumeroMetodoDePago,','); //auxArrayMetodos := aNumeroMetodoDePago.Split([',']);
. . .

**Comment by lcarrasco** [comment]
Gracias @thinkerbadal cierro el issue.
